### ISSUE TITLE
Trees spawn felled - Bug

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [desto-git/factorio-sapling-capsule#2]
I'm playing Factorio 1.1.5 with alien-biomes_0.6.3 mod. Studied the technology of your capsules and decided to plant some trees.

I made a couple of capsules and went to plant, but after using I saw this:
![image](https://user-images.githubusercontent.com/46845681/103478506-aae3c900-4de0-11eb-81f4-e33038502eaf.png)
Can you tell me how to fix this?

Update:

If you use the capsule next to an existing forest, the trees will appear correctly. Is this a feature of the mod or a flaw? Is it possible to plant trees on plains where they are not originally?

**Comment by desto-git** [comment]
This is a feature. See the first bullet point in the README.

I implemented it like that so that new trees will fit the surrounding environment. If there are no trees nearby, I cannot determine the fitting sprite to spawn. Planting a bright green broad-leaved tree in the middle of a desert would look odd.

With this limitation in mind, it is not currently possible to plant trees on plains. You need plant a line from an existing tree that is part of the sprite family would like to see.

**Comment by Eldrinn-Elantey** [comment]
Got it. Thanks for clarifying. Sorry for the stupid question.
